node_rate: 
  name: Ros nodes rate
  value: 100

planning:
  safe_dist:
    name: Safe distance from obstacles
    value: 5
  interpolation:
    name: Number of points to interpolate for each connection in PRM
    value: 30