node_rate: 
  name: Ros_rate
  value: 100
planning:
  iterations:
    name: Iterations for PRM
    value: 1000
  max_dist:
    name: Maximum distance between points in PRM
    value: 8
  safe_dist:
    name: Safe distance from obstacles
    value: 5
  interpolation:
    name: Number of points to interpolate for each connection in PRM
    value: 30