node_rate: 
  name: Ros_rate
  value: 100
classification:
  model:
    name: Model_ONNX
    path: "/home/puzzlebot/ws/src/rover_sentinel/rover_vision/model/best.onnx"
  classes:
    name: Classes_list
    list: ["Persona"]
  confidence:
    name: Conf_threshold
    value: 0.7
  isCuda:
    name: Enable_cuda
    value: True