node_rate: 
  name: Ros nodes rate
  value: 100

classification:
  model:
    name: Model in ONNX format
    path: "/home/puzzlebot/ws/src/rover_sentinel/rover_vision/model/best.onnx"
  confidence:
    name: Confidence threshold
    value: 0.6
  isCuda:
    name: Enable cuda (True or False)
    value: True