classification:
  model:
    name: Model_ONNX
    path: "/home/puzzlebot/catkin_ws/src/rover_sentinel/rover_vision/model/bestV5-25e.onnx"
  classes:
    name: Classes_list
    list: ["Fanta", "Pepsi", "Seven"]
  confidence:
    name: Conf_threshold
    value: 0.8
  isCuda:
    name: Enable_cuda
    value: True